import { StyleSheet } from "react-native";

const styles2 = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    paddingTop: 28,
    backgroundColor: "#fafafa",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#333",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#444",
  },
  label: {
    fontSize: 14,
    color: "#666",
    marginBottom: 2,
  },
  value: {
    fontSize: 14,
    color: "#000",
    marginBottom: 6,
    flexShrink: 1,
  },
  contactBox: {
    backgroundColor: "#f9f9f9",
    borderRadius: 16,
    padding: 12,
    marginTop: 8,
  },
  costRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  labelTotal: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#333",
  },
  valueTotal: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000",
  },
  map: {
    width: "100%",
    height: 140,
    borderRadius: 8,
    marginTop: 10,
  },
  paymentButton: {
    backgroundColor: "#007bff",
    paddingVertical: 14,
    borderRadius: 15,
    alignItems: "center",
    marginTop: 40,
    marginBottom: 30,
  },
  paymentText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#ddd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  infoContent: {
    flex: 1,
  },
  inlineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  editCircle: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: "#e0e0e0",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  iconImage: {
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  cardcosto: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
});

export default styles2;
